version: "3.7"

volumes:
  mongodb:

services:
  database:
    image: "mongo:4.1"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"

  bot:
    image: "registry.gitlab.com/lu-ci/sigma/apex-sigma:develop"
    build:
      context: .
    deploy:
      replicas: 1
    volumes:
      - type:      bind
        source:    "./config"
        target:    "/app/config"
        read_only: true
    depends_on:
      - "database"
